{{- if and .Values.calendarApi.enabled .Values.calendarApi.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redwood-calendar.fullname" . }}-api-pvc
  labels:
    {{- include "redwood-calendar.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.calendarApi.persistence.size }}
  {{- if .Values.calendarApi.persistence.storageClass }}
  storageClassName: {{ .Values.calendarApi.persistence.storageClass }}
  {{- end }}
{{- end }}