{{- if .Values.calendarFrontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redwood-calendar.fullname" . }}-frontend
  labels:
    {{- include "redwood-calendar.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.calendarFrontend.service.type }}
  ports:
  - port: {{ .Values.calendarFrontend.service.port }}
    targetPort: {{ .Values.calendarFrontend.service.targetPort }}
    name: http
  selector:
    {{- include "redwood-calendar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}