{{- if .Values.oauth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redwood-calendar.fullname" . }}-oauth-cookie
  labels:
    {{- include "redwood-calendar.labels" . | nindent 4 }}
stringData:
  session_secret: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
