apiVersion: v2
name: canopy-mcp-calendar
description: A Helm chart for Canopy AI Calendar System at RDU
type: application
version: 1.0.4
appVersion: "1.0.0"
keywords:
  - calendar
  - university
  - mcp
  - ai
home: https://github.com/rhoai-genaiops/mcp
icon: https://cdn-icons-png.flaticon.com/512/1067/1067374.png
sources:
  - https://github.com/rhoai-genaiops/mcp
maintainers:
  - name: ckavili
  - name: RHRolun
  - name: rcarrata